### ISSUE TITLE
Review Header and Navigation

### ISSUE THREAD

**Issue by learningcreature** [learningcreature/Designers-Page#2]
Hi Amit, Can you please make some changes to the header of the page and review navigation section too. Thanks

**Comment by kumaramit24apps** [comment]
Well, I am just working on it and I'll let you know tonight! :) Cheers

**Comment by learningcreature** [comment]
Your help will be greatly appreciated! :)

**Comment by kumaramit24apps** [comment]
I am not able to fix the problem you are asking for ! Fix on your own!

Just kidding ! We're just learning git and github dude

**Comment by kumaramit24apps** [comment]
Bbbyeee

**Comment by kumaramit24apps** [comment]
hahah right ! :)
